name: 'Node'

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout ğŸ›¬'
        run: actions/checkout@v4

      - name: 'Setup node âš™ï¸'
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: 'Install dependencies ğŸ“¦'
        run: npm ci

      - name: 'Build typescript'
        run: npm run build && find dist/main.js

      - name: 'Run tests ğŸ§ª'
        run: npm test
